version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    detailed:
        format: '[%(levelname)s:%(asctime)s:%(filename)s:%(lineno)s - %(funcName)20s() ] %(message)s'
        datefmt:  '%Y-%m-%d %I:%M:%S%p'


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: detailed
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: shim_debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detailed
        filename: shim_info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: detailed
        filename: shim_errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


# define logging levels, and logging handlers for your modules here
# each section should define a logging setup for a specific module in
# your code. If you dont define any loggers, the root logger will process
# the logging messages
loggers:
    contact:
        level: DEBUG
        handlers: [console, debug_file_handler]
        propagate: no
# The logger for the root level directory, which is 'newman'
root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]